name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-createvideov5:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push docker image
      run: |
        docker build . --push --file Dockerfile \
        --tag ghcr.io/adityachallapally/createvideov5:${GITHUB_REF#refs/*/}-${{ github.run_id }} \
        --tag ghcr.io/adityachallapally/createvideov5:latest
